/**
 * LSP Request and Notification namespaces
 * Auto-generated by scripts/generate-protocol-types.ts
 *
 * DO NOT EDIT MANUALLY - regenerate using: pnpm run generate:protocol
 */

import type {
  ApplyWorkspaceEditParams,
  ApplyWorkspaceEditResult,
  CallHierarchyClientCapabilities,
  CallHierarchyIncomingCall,
  CallHierarchyIncomingCallsParams,
  CallHierarchyItem,
  CallHierarchyOptions,
  CallHierarchyOutgoingCall,
  CallHierarchyOutgoingCallsParams,
  CallHierarchyPrepareParams,
  CallHierarchyRegistrationOptions,
  CodeAction,
  CodeActionClientCapabilities,
  CodeActionOptions,
  CodeActionParams,
  CodeActionRegistrationOptions,
  CodeLens,
  CodeLensClientCapabilities,
  CodeLensOptions,
  CodeLensParams,
  CodeLensRegistrationOptions,
  ColorInformation,
  ColorPresentation,
  ColorPresentationParams,
  Command,
  CompletionClientCapabilities,
  CompletionItem,
  CompletionList,
  CompletionOptions,
  CompletionParams,
  CompletionRegistrationOptions,
  ConfigurationParams,
  CreateFilesParams,
  Declaration,
  DeclarationClientCapabilities,
  DeclarationOptions,
  DeclarationParams,
  DeclarationRegistrationOptions,
  Definition,
  DefinitionClientCapabilities,
  DefinitionOptions,
  DefinitionParams,
  DefinitionRegistrationOptions,
  DeleteFilesParams,
  DiagnosticClientCapabilities,
  DiagnosticOptions,
  DiagnosticRegistrationOptions,
  DidChangeConfigurationParams,
  DidChangeConfigurationRegistrationOptions,
  DidChangeNotebookDocumentParams,
  DidChangeTextDocumentParams,
  DidChangeWatchedFilesParams,
  DidChangeWatchedFilesRegistrationOptions,
  DidChangeWorkspaceFoldersParams,
  DidCloseNotebookDocumentParams,
  DidCloseTextDocumentParams,
  DidOpenNotebookDocumentParams,
  DidOpenTextDocumentParams,
  DidSaveNotebookDocumentParams,
  DidSaveTextDocumentParams,
  DocumentColorOptions,
  DocumentColorParams,
  DocumentColorRegistrationOptions,
  DocumentDiagnosticParams,
  DocumentDiagnosticReport,
  DocumentFormattingClientCapabilities,
  DocumentFormattingOptions,
  DocumentFormattingParams,
  DocumentFormattingRegistrationOptions,
  DocumentHighlight,
  DocumentHighlightClientCapabilities,
  DocumentHighlightOptions,
  DocumentHighlightParams,
  DocumentHighlightRegistrationOptions,
  DocumentLink,
  DocumentLinkClientCapabilities,
  DocumentLinkOptions,
  DocumentLinkParams,
  DocumentLinkRegistrationOptions,
  DocumentOnTypeFormattingClientCapabilities,
  DocumentOnTypeFormattingOptions,
  DocumentOnTypeFormattingParams,
  DocumentOnTypeFormattingRegistrationOptions,
  DocumentRangeFormattingClientCapabilities,
  DocumentRangeFormattingOptions,
  DocumentRangeFormattingParams,
  DocumentRangeFormattingRegistrationOptions,
  DocumentRangesFormattingParams,
  DocumentSymbol,
  DocumentSymbolClientCapabilities,
  DocumentSymbolOptions,
  DocumentSymbolParams,
  DocumentSymbolRegistrationOptions,
  ExecuteCommandClientCapabilities,
  ExecuteCommandOptions,
  ExecuteCommandParams,
  ExecuteCommandRegistrationOptions,
  FileOperationClientCapabilities,
  FileOperationOptions,
  FileOperationRegistrationOptions,
  FoldingRange,
  FoldingRangeClientCapabilities,
  FoldingRangeOptions,
  FoldingRangeParams,
  FoldingRangeRegistrationOptions,
  Hover,
  HoverClientCapabilities,
  HoverOptions,
  HoverParams,
  HoverRegistrationOptions,
  ImplementationOptions,
  ImplementationParams,
  ImplementationRegistrationOptions,
  InitializeParams,
  InitializeResult,
  InitializedParams,
  InlayHint,
  InlayHintClientCapabilities,
  InlayHintOptions,
  InlayHintParams,
  InlayHintRegistrationOptions,
  InlineCompletionClientCapabilities,
  InlineCompletionItem,
  InlineCompletionList,
  InlineCompletionOptions,
  InlineCompletionParams,
  InlineCompletionRegistrationOptions,
  InlineValue,
  InlineValueClientCapabilities,
  InlineValueOptions,
  InlineValueParams,
  InlineValueRegistrationOptions,
  LinkedEditingRangeClientCapabilities,
  LinkedEditingRangeOptions,
  LinkedEditingRangeParams,
  LinkedEditingRangeRegistrationOptions,
  LinkedEditingRanges,
  Location,
  LocationLink,
  LogMessageParams,
  MessageActionItem,
  Moniker,
  MonikerClientCapabilities,
  MonikerOptions,
  MonikerParams,
  MonikerRegistrationOptions,
  PrepareRenameParams,
  PrepareRenameResult,
  PublishDiagnosticsParams,
  ReferenceClientCapabilities,
  ReferenceOptions,
  ReferenceParams,
  ReferenceRegistrationOptions,
  RegistrationParams,
  RenameClientCapabilities,
  RenameFilesParams,
  RenameOptions,
  RenameParams,
  RenameRegistrationOptions,
  SelectionRange,
  SelectionRangeClientCapabilities,
  SelectionRangeOptions,
  SelectionRangeParams,
  SelectionRangeRegistrationOptions,
  SemanticTokens,
  SemanticTokensClientCapabilities,
  SemanticTokensDelta,
  SemanticTokensDeltaParams,
  SemanticTokensOptions,
  SemanticTokensParams,
  SemanticTokensRangeParams,
  SemanticTokensRegistrationOptions,
  ShowDocumentParams,
  ShowDocumentResult,
  ShowMessageParams,
  ShowMessageRequestParams,
  SignatureHelp,
  SignatureHelpClientCapabilities,
  SignatureHelpOptions,
  SignatureHelpParams,
  SignatureHelpRegistrationOptions,
  SymbolInformation,
  TextDocumentChangeRegistrationOptions,
  TextDocumentClientCapabilities,
  TextDocumentRegistrationOptions,
  TextDocumentSaveRegistrationOptions,
  TextEdit,
  TypeDefinitionOptions,
  TypeDefinitionParams,
  TypeDefinitionRegistrationOptions,
  TypeHierarchyClientCapabilities,
  TypeHierarchyItem,
  TypeHierarchyOptions,
  TypeHierarchyPrepareParams,
  TypeHierarchyRegistrationOptions,
  TypeHierarchySubtypesParams,
  TypeHierarchySupertypesParams,
  UnregistrationParams,
  WillSaveTextDocumentParams,
  WorkDoneProgressCancelParams,
  WorkDoneProgressCreateParams,
  WorkDoneProgressOptions,
  WorkspaceDiagnosticParams,
  WorkspaceDiagnosticReport,
  WorkspaceEdit,
  WorkspaceFolder,
  WorkspaceSymbol,
  WorkspaceSymbolClientCapabilities,
  WorkspaceSymbolOptions,
  WorkspaceSymbolParams,
  WorkspaceSymbolRegistrationOptions
} from './types.js';

export type LSPRequest = {
  TextDocument: {
    CallHierarchyPrepare: {
      Method: 'textDocument/prepareCallHierarchy';
      Params: CallHierarchyPrepareParams;
      Result?: CallHierarchyItem[] | null;
      ClientCapability: CallHierarchyClientCapabilities;
      ServerCapability: 'callHierarchyPrepareProvider';
      Options: CallHierarchyOptions;
      RegistrationOptions: CallHierarchyRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentColor: {
      Method: 'textDocument/documentColor';
      Params: DocumentColorParams;
      Result?: ColorInformation[];
      ClientCapability: void;
      ServerCapability: 'documentColorProvider';
      Options: DocumentColorOptions;
      RegistrationOptions: DocumentColorRegistrationOptions;
      Direction: 'clientToServer';
    };
    ColorPresentation: {
      Method: 'textDocument/colorPresentation';
      Params: ColorPresentationParams;
      Result?: ColorPresentation[];
      ClientCapability: void;
      ServerCapability: 'colorPresentationProvider';
      Options: void;
      RegistrationOptions: WorkDoneProgressOptions & TextDocumentRegistrationOptions;
      Direction: 'clientToServer';
    };
    WillSaveTextDocumentWaitUntil: {
      Method: 'textDocument/willSaveWaitUntil';
      Params: WillSaveTextDocumentParams;
      Result?: TextEdit[] | null;
      ClientCapability: TextDocumentClientCapabilities;
      ServerCapability: 'willSaveTextDocumentWaitUntilProvider';
      Options: void;
      RegistrationOptions: TextDocumentRegistrationOptions;
      Direction: 'clientToServer';
    };
    Completion: {
      Method: 'textDocument/completion';
      Params: CompletionParams;
      Result?: CompletionList | CompletionItem[] | null;
      ClientCapability: CompletionClientCapabilities;
      ServerCapability: 'completionProvider';
      Options: CompletionOptions;
      RegistrationOptions: CompletionRegistrationOptions;
      Direction: 'clientToServer';
    };
    Hover: {
      Method: 'textDocument/hover';
      Params: HoverParams;
      Result?: Hover | null;
      ClientCapability: HoverClientCapabilities;
      ServerCapability: 'hoverProvider';
      Options: HoverOptions;
      RegistrationOptions: HoverRegistrationOptions;
      Direction: 'clientToServer';
    };
    SignatureHelp: {
      Method: 'textDocument/signatureHelp';
      Params: SignatureHelpParams;
      Result?: SignatureHelp | null;
      ClientCapability: SignatureHelpClientCapabilities;
      ServerCapability: 'signatureHelpProvider';
      Options: SignatureHelpOptions;
      RegistrationOptions: SignatureHelpRegistrationOptions;
      Direction: 'clientToServer';
    };
    Definition: {
      Method: 'textDocument/definition';
      Params: DefinitionParams;
      Result?: Definition | LocationLink[] | null;
      ClientCapability: DefinitionClientCapabilities;
      ServerCapability: 'definitionProvider';
      Options: DefinitionOptions;
      RegistrationOptions: DefinitionRegistrationOptions;
      Direction: 'clientToServer';
    };
    References: {
      Method: 'textDocument/references';
      Params: ReferenceParams;
      Result?: Location[] | null;
      ClientCapability: ReferenceClientCapabilities;
      ServerCapability: 'referencesProvider';
      Options: ReferenceOptions;
      RegistrationOptions: ReferenceRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentHighlight: {
      Method: 'textDocument/documentHighlight';
      Params: DocumentHighlightParams;
      Result?: DocumentHighlight[] | null;
      ClientCapability: DocumentHighlightClientCapabilities;
      ServerCapability: 'documentHighlightProvider';
      Options: DocumentHighlightOptions;
      RegistrationOptions: DocumentHighlightRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentSymbol: {
      Method: 'textDocument/documentSymbol';
      Params: DocumentSymbolParams;
      Result?: DocumentSymbol[] | SymbolInformation[] | null;
      ClientCapability: DocumentSymbolClientCapabilities;
      ServerCapability: 'documentSymbolProvider';
      Options: DocumentSymbolOptions;
      RegistrationOptions: DocumentSymbolRegistrationOptions;
      Direction: 'clientToServer';
    };
    CodeAction: {
      Method: 'textDocument/codeAction';
      Params: CodeActionParams;
      Result?: (Command | CodeAction)[] | null;
      ClientCapability: CodeActionClientCapabilities;
      ServerCapability: 'codeActionProvider';
      Options: CodeActionOptions;
      RegistrationOptions: CodeActionRegistrationOptions;
      Direction: 'clientToServer';
    };
    CodeLens: {
      Method: 'textDocument/codeLens';
      Params: CodeLensParams;
      Result?: CodeLens[] | null;
      ClientCapability: CodeLensClientCapabilities;
      ServerCapability: 'codeLensProvider';
      Options: CodeLensOptions;
      RegistrationOptions: CodeLensRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentLink: {
      Method: 'textDocument/documentLink';
      Params: DocumentLinkParams;
      Result?: DocumentLink[] | null;
      ClientCapability: DocumentLinkClientCapabilities;
      ServerCapability: 'documentLinkProvider';
      Options: DocumentLinkOptions;
      RegistrationOptions: DocumentLinkRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentFormatting: {
      Method: 'textDocument/formatting';
      Params: DocumentFormattingParams;
      Result?: TextEdit[] | null;
      ClientCapability: DocumentFormattingClientCapabilities;
      ServerCapability: 'documentFormattingProvider';
      Options: DocumentFormattingOptions;
      RegistrationOptions: DocumentFormattingRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentRangeFormatting: {
      Method: 'textDocument/rangeFormatting';
      Params: DocumentRangeFormattingParams;
      Result?: TextEdit[] | null;
      ClientCapability: DocumentRangeFormattingClientCapabilities;
      ServerCapability: 'documentRangeFormattingProvider';
      Options: DocumentRangeFormattingOptions;
      RegistrationOptions: DocumentRangeFormattingRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentRangesFormatting: {
      Method: 'textDocument/rangesFormatting';
      Params: DocumentRangesFormattingParams;
      Result?: TextEdit[] | null;
      ClientCapability: DocumentRangeFormattingClientCapabilities;
      ServerCapability: 'documentRangesFormattingProvider';
      Options: DocumentRangeFormattingOptions;
      RegistrationOptions: DocumentRangeFormattingRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentOnTypeFormatting: {
      Method: 'textDocument/onTypeFormatting';
      Params: DocumentOnTypeFormattingParams;
      Result?: TextEdit[] | null;
      ClientCapability: DocumentOnTypeFormattingClientCapabilities;
      ServerCapability: 'documentOnTypeFormattingProvider';
      Options: DocumentOnTypeFormattingOptions;
      RegistrationOptions: DocumentOnTypeFormattingRegistrationOptions;
      Direction: 'clientToServer';
    };
    Rename: {
      Method: 'textDocument/rename';
      Params: RenameParams;
      Result?: WorkspaceEdit | null;
      ClientCapability: RenameClientCapabilities;
      ServerCapability: 'renameProvider';
      Options: RenameOptions;
      RegistrationOptions: RenameRegistrationOptions;
      Direction: 'clientToServer';
    };
    PrepareRename: {
      Method: 'textDocument/prepareRename';
      Params: PrepareRenameParams;
      Result?: PrepareRenameResult | null;
      ClientCapability: void;
      ServerCapability: 'prepareRenameProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    Declaration: {
      Method: 'textDocument/declaration';
      Params: DeclarationParams;
      Result?: Declaration | LocationLink[] | null;
      ClientCapability: DeclarationClientCapabilities;
      ServerCapability: 'declarationProvider';
      Options: DeclarationOptions;
      RegistrationOptions: DeclarationRegistrationOptions;
      Direction: 'clientToServer';
    };
    DocumentDiagnostic: {
      Method: 'textDocument/diagnostic';
      Params: DocumentDiagnosticParams;
      Result?: DocumentDiagnosticReport;
      ClientCapability: DiagnosticClientCapabilities;
      ServerCapability: 'documentDiagnosticProvider';
      Options: DiagnosticOptions;
      RegistrationOptions: DiagnosticRegistrationOptions;
      Direction: 'clientToServer';
    };
    FoldingRange: {
      Method: 'textDocument/foldingRange';
      Params: FoldingRangeParams;
      Result?: FoldingRange[] | null;
      ClientCapability: FoldingRangeClientCapabilities;
      ServerCapability: 'foldingRangeProvider';
      Options: FoldingRangeOptions;
      RegistrationOptions: FoldingRangeRegistrationOptions;
      Direction: 'clientToServer';
    };
    Implementation: {
      Method: 'textDocument/implementation';
      Params: ImplementationParams;
      Result?: Definition | LocationLink[] | null;
      ClientCapability: void;
      ServerCapability: 'implementationProvider';
      Options: ImplementationOptions;
      RegistrationOptions: ImplementationRegistrationOptions;
      Direction: 'clientToServer';
    };
    InlayHint: {
      Method: 'textDocument/inlayHint';
      Params: InlayHintParams;
      Result?: InlayHint[] | null;
      ClientCapability: InlayHintClientCapabilities;
      ServerCapability: 'inlayHintProvider';
      Options: InlayHintOptions;
      RegistrationOptions: InlayHintRegistrationOptions;
      Direction: 'clientToServer';
    };
    InlineCompletion: {
      Method: 'textDocument/inlineCompletion';
      Params: InlineCompletionParams;
      Result?: InlineCompletionList | InlineCompletionItem[] | null;
      ClientCapability: InlineCompletionClientCapabilities;
      ServerCapability: 'inlineCompletionProvider';
      Options: InlineCompletionOptions;
      RegistrationOptions: InlineCompletionRegistrationOptions;
      Direction: 'clientToServer';
    };
    InlineValue: {
      Method: 'textDocument/inlineValue';
      Params: InlineValueParams;
      Result?: InlineValue[] | null;
      ClientCapability: InlineValueClientCapabilities;
      ServerCapability: 'inlineValueProvider';
      Options: InlineValueOptions;
      RegistrationOptions: InlineValueRegistrationOptions;
      Direction: 'clientToServer';
    };
    LinkedEditingRange: {
      Method: 'textDocument/linkedEditingRange';
      Params: LinkedEditingRangeParams;
      Result?: LinkedEditingRanges | null;
      ClientCapability: LinkedEditingRangeClientCapabilities;
      ServerCapability: 'linkedEditingRangeProvider';
      Options: LinkedEditingRangeOptions;
      RegistrationOptions: LinkedEditingRangeRegistrationOptions;
      Direction: 'clientToServer';
    };
    Moniker: {
      Method: 'textDocument/moniker';
      Params: MonikerParams;
      Result?: Moniker[] | null;
      ClientCapability: MonikerClientCapabilities;
      ServerCapability: 'monikerProvider';
      Options: MonikerOptions;
      RegistrationOptions: MonikerRegistrationOptions;
      Direction: 'clientToServer';
    };
    SelectionRange: {
      Method: 'textDocument/selectionRange';
      Params: SelectionRangeParams;
      Result?: SelectionRange[] | null;
      ClientCapability: SelectionRangeClientCapabilities;
      ServerCapability: 'selectionRangeProvider';
      Options: SelectionRangeOptions;
      RegistrationOptions: SelectionRangeRegistrationOptions;
      Direction: 'clientToServer';
    };
    SemanticTokens: {
      Method: 'textDocument/semanticTokens/full';
      Params: SemanticTokensParams;
      Result?: SemanticTokens | null;
      ClientCapability: SemanticTokensClientCapabilities;
      ServerCapability: 'semanticTokensProvider';
      Options: SemanticTokensOptions;
      RegistrationOptions: SemanticTokensRegistrationOptions;
      Direction: 'clientToServer';
    };
    SemanticTokensDelta: {
      Method: 'textDocument/semanticTokens/full/delta';
      Params: SemanticTokensDeltaParams;
      Result?: SemanticTokens | SemanticTokensDelta | null;
      ClientCapability: SemanticTokensClientCapabilities;
      ServerCapability: 'semanticTokensDeltaProvider';
      Options: SemanticTokensOptions;
      RegistrationOptions: SemanticTokensRegistrationOptions;
      Direction: 'clientToServer';
    };
    SemanticTokensRange: {
      Method: 'textDocument/semanticTokens/range';
      Params: SemanticTokensRangeParams;
      Result?: SemanticTokens | null;
      ClientCapability: void;
      ServerCapability: 'semanticTokensRangeProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    TypeDefinition: {
      Method: 'textDocument/typeDefinition';
      Params: TypeDefinitionParams;
      Result?: Definition | LocationLink[] | null;
      ClientCapability: void;
      ServerCapability: 'typeDefinitionProvider';
      Options: TypeDefinitionOptions;
      RegistrationOptions: TypeDefinitionRegistrationOptions;
      Direction: 'clientToServer';
    };
    TypeHierarchyPrepare: {
      Method: 'textDocument/prepareTypeHierarchy';
      Params: TypeHierarchyPrepareParams;
      Result?: TypeHierarchyItem[] | null;
      ClientCapability: TypeHierarchyClientCapabilities;
      ServerCapability: 'typeHierarchyPrepareProvider';
      Options: TypeHierarchyOptions;
      RegistrationOptions: TypeHierarchyRegistrationOptions;
      Direction: 'clientToServer';
    };
  };
  CallHierarchy: {
    CallHierarchyIncomingCalls: {
      Method: 'callHierarchy/incomingCalls';
      Params: CallHierarchyIncomingCallsParams;
      Result?: CallHierarchyIncomingCall[] | null;
      ClientCapability: void;
      ServerCapability: 'callHierarchyIncomingCallsProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    CallHierarchyOutgoingCalls: {
      Method: 'callHierarchy/outgoingCalls';
      Params: CallHierarchyOutgoingCallsParams;
      Result?: CallHierarchyOutgoingCall[] | null;
      ClientCapability: void;
      ServerCapability: 'callHierarchyOutgoingCallsProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  Workspace: {
    Configuration: {
      Method: 'workspace/configuration';
      Params: ConfigurationParams;
      Result?: any[];
      ClientCapability: void;
      ServerCapability: 'configurationProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    WorkspaceSymbol: {
      Method: 'workspace/symbol';
      Params: WorkspaceSymbolParams;
      Result?: SymbolInformation[] | WorkspaceSymbol[] | null;
      ClientCapability: WorkspaceSymbolClientCapabilities;
      ServerCapability: 'workspaceSymbolProvider';
      Options: WorkspaceSymbolOptions;
      RegistrationOptions: WorkspaceSymbolRegistrationOptions;
      Direction: 'clientToServer';
    };
    ExecuteCommand: {
      Method: 'workspace/executeCommand';
      Params: ExecuteCommandParams;
      Result?: any;
      ClientCapability: ExecuteCommandClientCapabilities;
      ServerCapability: 'executeCommandProvider';
      Options: ExecuteCommandOptions;
      RegistrationOptions: ExecuteCommandRegistrationOptions;
      Direction: 'clientToServer';
    };
    ApplyWorkspaceEdit: {
      Method: 'workspace/applyEdit';
      Params: ApplyWorkspaceEditParams;
      Result?: ApplyWorkspaceEditResult;
      ClientCapability: void;
      ServerCapability: 'applyWorkspaceEditProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    WorkspaceDiagnostic: {
      Method: 'workspace/diagnostic';
      Params: WorkspaceDiagnosticParams;
      Result?: WorkspaceDiagnosticReport;
      ClientCapability: void;
      ServerCapability: 'workspaceDiagnosticProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    WillCreateFiles: {
      Method: 'workspace/willCreateFiles';
      Params: CreateFilesParams;
      Result?: WorkspaceEdit | null;
      ClientCapability: FileOperationClientCapabilities;
      ServerCapability: 'willCreateFilesProvider';
      Options: FileOperationOptions;
      RegistrationOptions: FileOperationRegistrationOptions;
      Direction: 'clientToServer';
    };
    WillRenameFiles: {
      Method: 'workspace/willRenameFiles';
      Params: RenameFilesParams;
      Result?: WorkspaceEdit | null;
      ClientCapability: FileOperationClientCapabilities;
      ServerCapability: 'willRenameFilesProvider';
      Options: FileOperationOptions;
      RegistrationOptions: FileOperationRegistrationOptions;
      Direction: 'clientToServer';
    };
    WillDeleteFiles: {
      Method: 'workspace/willDeleteFiles';
      Params: DeleteFilesParams;
      Result?: WorkspaceEdit | null;
      ClientCapability: FileOperationClientCapabilities;
      ServerCapability: 'willDeleteFilesProvider';
      Options: FileOperationOptions;
      RegistrationOptions: FileOperationRegistrationOptions;
      Direction: 'clientToServer';
    };
    WorkspaceFolders: {
      Method: 'workspace/workspaceFolders';
      Params: WorkspaceFolder[] | null;
      Result?: never;
      ClientCapability: void;
      ServerCapability: 'workspaceFoldersProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
  };
  Client: {
    Registration: {
      Method: 'client/registerCapability';
      Params: RegistrationParams;
      Result?: void;
      ClientCapability: void;
      ServerCapability: 'registrationProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    Unregistration: {
      Method: 'client/unregisterCapability';
      Params: UnregistrationParams;
      Result?: void;
      ClientCapability: void;
      ServerCapability: 'unregistrationProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
  };
  General: {
    Initialize: {
      Method: 'initialize';
      Params: InitializeParams;
      Result?: InitializeResult<any>;
      ClientCapability: void;
      ServerCapability: 'initializeProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    Shutdown: {
      Method: 'shutdown';
      Params: void;
      Result?: never;
      ClientCapability: void;
      ServerCapability: 'shutdownProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  Window: {
    ShowMessageRequest: {
      Method: 'window/showMessageRequest';
      Params: ShowMessageRequestParams;
      Result?: MessageActionItem | null;
      ClientCapability: void;
      ServerCapability: 'showMessageProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    WorkDoneProgressCreate: {
      Method: 'window/workDoneProgress/create';
      Params: WorkDoneProgressCreateParams;
      Result?: void;
      ClientCapability: void;
      ServerCapability: 'workDoneProgressCreateProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    ShowDocument: {
      Method: 'window/showDocument';
      Params: ShowDocumentParams;
      Result?: ShowDocumentResult;
      ClientCapability: void;
      ServerCapability: 'showDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
  };
  CompletionItem: {
    CompletionResolve: {
      Method: 'completionItem/resolve';
      Params: CompletionItem;
      Result?: CompletionItem;
      ClientCapability: void;
      ServerCapability: 'completionResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  CodeAction: {
    CodeActionResolve: {
      Method: 'codeAction/resolve';
      Params: CodeAction;
      Result?: CodeAction;
      ClientCapability: void;
      ServerCapability: 'codeActionResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  WorkspaceSymbol: {
    WorkspaceSymbolResolve: {
      Method: 'workspaceSymbol/resolve';
      Params: WorkspaceSymbol;
      Result?: WorkspaceSymbol;
      ClientCapability: void;
      ServerCapability: 'workspaceSymbolResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  CodeLens: {
    CodeLensResolve: {
      Method: 'codeLens/resolve';
      Params: CodeLens;
      Result?: CodeLens;
      ClientCapability: void;
      ServerCapability: 'codeLensResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  DocumentLink: {
    DocumentLinkResolve: {
      Method: 'documentLink/resolve';
      Params: DocumentLink;
      Result?: DocumentLink;
      ClientCapability: void;
      ServerCapability: 'documentLinkResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  InlayHint: {
    InlayHintResolve: {
      Method: 'inlayHint/resolve';
      Params: InlayHint;
      Result?: InlayHint;
      ClientCapability: void;
      ServerCapability: 'inlayHintResolveProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  TypeHierarchy: {
    TypeHierarchySupertypes: {
      Method: 'typeHierarchy/supertypes';
      Params: TypeHierarchySupertypesParams;
      Result?: TypeHierarchyItem[] | null;
      ClientCapability: void;
      ServerCapability: 'typeHierarchySupertypesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    TypeHierarchySubtypes: {
      Method: 'typeHierarchy/subtypes';
      Params: TypeHierarchySubtypesParams;
      Result?: TypeHierarchyItem[] | null;
      ClientCapability: void;
      ServerCapability: 'typeHierarchySubtypesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
};

export type LSPNotification = {
  General: {
    Initialized: {
      Method: 'initialized';
      Params: InitializedParams;
      ClientCapability: void;
      ServerCapability: 'initializedProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  Workspace: {
    DidChangeConfiguration: {
      Method: 'workspace/didChangeConfiguration';
      Params: DidChangeConfigurationParams;
      ClientCapability: void;
      ServerCapability: 'didChangeConfigurationProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidChangeWatchedFiles: {
      Method: 'workspace/didChangeWatchedFiles';
      Params: DidChangeWatchedFilesParams;
      ClientCapability: void;
      ServerCapability: 'didChangeWatchedFilesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidCreateFiles: {
      Method: 'workspace/didCreateFiles';
      Params: CreateFilesParams;
      ClientCapability: void;
      ServerCapability: 'didCreateFilesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidRenameFiles: {
      Method: 'workspace/didRenameFiles';
      Params: RenameFilesParams;
      ClientCapability: void;
      ServerCapability: 'didRenameFilesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidDeleteFiles: {
      Method: 'workspace/didDeleteFiles';
      Params: DeleteFilesParams;
      ClientCapability: void;
      ServerCapability: 'didDeleteFilesProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidChangeWorkspaceFolders: {
      Method: 'workspace/didChangeWorkspaceFolders';
      Params: DidChangeWorkspaceFoldersParams;
      ClientCapability: void;
      ServerCapability: 'didChangeWorkspaceFoldersProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  Window: {
    ShowMessage: {
      Method: 'window/showMessage';
      Params: ShowMessageParams;
      ClientCapability: void;
      ServerCapability: 'showMessageProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    LogMessage: {
      Method: 'window/logMessage';
      Params: LogMessageParams;
      ClientCapability: void;
      ServerCapability: 'logMessageProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
    WorkDoneProgressCancel: {
      Method: 'window/workDoneProgress/cancel';
      Params: WorkDoneProgressCancelParams;
      ClientCapability: void;
      ServerCapability: 'workDoneProgressCancelProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
  Telemetry: {
    TelemetryEvent: {
      Method: 'telemetry/event';
      Params: any;
      ClientCapability: void;
      ServerCapability: 'telemetryEventProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
  };
  TextDocument: {
    DidOpenTextDocument: {
      Method: 'textDocument/didOpen';
      Params: DidOpenTextDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didOpenTextDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidChangeTextDocument: {
      Method: 'textDocument/didChange';
      Params: DidChangeTextDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didChangeTextDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidCloseTextDocument: {
      Method: 'textDocument/didClose';
      Params: DidCloseTextDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didCloseTextDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidSaveTextDocument: {
      Method: 'textDocument/didSave';
      Params: DidSaveTextDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didSaveTextDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    WillSaveTextDocument: {
      Method: 'textDocument/willSave';
      Params: WillSaveTextDocumentParams;
      ClientCapability: void;
      ServerCapability: 'willSaveTextDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    PublishDiagnostics: {
      Method: 'textDocument/publishDiagnostics';
      Params: PublishDiagnosticsParams;
      ClientCapability: void;
      ServerCapability: 'publishDiagnosticsProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'serverToClient';
    };
  };
  NotebookDocument: {
    DidOpenNotebookDocument: {
      Method: 'notebookDocument/didOpen';
      Params: DidOpenNotebookDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didOpenNotebookDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidChangeNotebookDocument: {
      Method: 'notebookDocument/didChange';
      Params: DidChangeNotebookDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didChangeNotebookDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidSaveNotebookDocument: {
      Method: 'notebookDocument/didSave';
      Params: DidSaveNotebookDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didSaveNotebookDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
    DidCloseNotebookDocument: {
      Method: 'notebookDocument/didClose';
      Params: DidCloseNotebookDocumentParams;
      ClientCapability: void;
      ServerCapability: 'didCloseNotebookDocumentProvider';
      Options: void;
      RegistrationOptions: void;
      Direction: 'clientToServer';
    };
  };
};

export const LSPRequest = {
  TextDocument: {
    CallHierarchyPrepare: {
      Method: 'textDocument/prepareCallHierarchy' as const,
      ServerCapability: 'callHierarchyPrepareProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentColor: {
      Method: 'textDocument/documentColor' as const,
      ServerCapability: 'documentColorProvider' as const,
      Direction: 'clientToServer' as const
    },
    ColorPresentation: {
      Method: 'textDocument/colorPresentation' as const,
      ServerCapability: 'colorPresentationProvider' as const,
      Direction: 'clientToServer' as const
    },
    WillSaveTextDocumentWaitUntil: {
      Method: 'textDocument/willSaveWaitUntil' as const,
      ServerCapability: 'willSaveTextDocumentWaitUntilProvider' as const,
      Direction: 'clientToServer' as const
    },
    Completion: {
      Method: 'textDocument/completion' as const,
      ServerCapability: 'completionProvider' as const,
      Direction: 'clientToServer' as const
    },
    Hover: {
      Method: 'textDocument/hover' as const,
      ServerCapability: 'hoverProvider' as const,
      Direction: 'clientToServer' as const
    },
    SignatureHelp: {
      Method: 'textDocument/signatureHelp' as const,
      ServerCapability: 'signatureHelpProvider' as const,
      Direction: 'clientToServer' as const
    },
    Definition: {
      Method: 'textDocument/definition' as const,
      ServerCapability: 'definitionProvider' as const,
      Direction: 'clientToServer' as const
    },
    References: {
      Method: 'textDocument/references' as const,
      ServerCapability: 'referencesProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentHighlight: {
      Method: 'textDocument/documentHighlight' as const,
      ServerCapability: 'documentHighlightProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentSymbol: {
      Method: 'textDocument/documentSymbol' as const,
      ServerCapability: 'documentSymbolProvider' as const,
      Direction: 'clientToServer' as const
    },
    CodeAction: {
      Method: 'textDocument/codeAction' as const,
      ServerCapability: 'codeActionProvider' as const,
      Direction: 'clientToServer' as const
    },
    CodeLens: {
      Method: 'textDocument/codeLens' as const,
      ServerCapability: 'codeLensProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentLink: {
      Method: 'textDocument/documentLink' as const,
      ServerCapability: 'documentLinkProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentFormatting: {
      Method: 'textDocument/formatting' as const,
      ServerCapability: 'documentFormattingProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentRangeFormatting: {
      Method: 'textDocument/rangeFormatting' as const,
      ServerCapability: 'documentRangeFormattingProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentRangesFormatting: {
      Method: 'textDocument/rangesFormatting' as const,
      ServerCapability: 'documentRangesFormattingProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentOnTypeFormatting: {
      Method: 'textDocument/onTypeFormatting' as const,
      ServerCapability: 'documentOnTypeFormattingProvider' as const,
      Direction: 'clientToServer' as const
    },
    Rename: {
      Method: 'textDocument/rename' as const,
      ServerCapability: 'renameProvider' as const,
      Direction: 'clientToServer' as const
    },
    PrepareRename: {
      Method: 'textDocument/prepareRename' as const,
      ServerCapability: 'prepareRenameProvider' as const,
      Direction: 'clientToServer' as const
    },
    Declaration: {
      Method: 'textDocument/declaration' as const,
      ServerCapability: 'declarationProvider' as const,
      Direction: 'clientToServer' as const
    },
    DocumentDiagnostic: {
      Method: 'textDocument/diagnostic' as const,
      ServerCapability: 'documentDiagnosticProvider' as const,
      Direction: 'clientToServer' as const
    },
    FoldingRange: {
      Method: 'textDocument/foldingRange' as const,
      ServerCapability: 'foldingRangeProvider' as const,
      Direction: 'clientToServer' as const
    },
    Implementation: {
      Method: 'textDocument/implementation' as const,
      ServerCapability: 'implementationProvider' as const,
      Direction: 'clientToServer' as const
    },
    InlayHint: {
      Method: 'textDocument/inlayHint' as const,
      ServerCapability: 'inlayHintProvider' as const,
      Direction: 'clientToServer' as const
    },
    InlineCompletion: {
      Method: 'textDocument/inlineCompletion' as const,
      ServerCapability: 'inlineCompletionProvider' as const,
      Direction: 'clientToServer' as const
    },
    InlineValue: {
      Method: 'textDocument/inlineValue' as const,
      ServerCapability: 'inlineValueProvider' as const,
      Direction: 'clientToServer' as const
    },
    LinkedEditingRange: {
      Method: 'textDocument/linkedEditingRange' as const,
      ServerCapability: 'linkedEditingRangeProvider' as const,
      Direction: 'clientToServer' as const
    },
    Moniker: {
      Method: 'textDocument/moniker' as const,
      ServerCapability: 'monikerProvider' as const,
      Direction: 'clientToServer' as const
    },
    SelectionRange: {
      Method: 'textDocument/selectionRange' as const,
      ServerCapability: 'selectionRangeProvider' as const,
      Direction: 'clientToServer' as const
    },
    SemanticTokens: {
      Method: 'textDocument/semanticTokens/full' as const,
      ServerCapability: 'semanticTokensProvider' as const,
      Direction: 'clientToServer' as const
    },
    SemanticTokensDelta: {
      Method: 'textDocument/semanticTokens/full/delta' as const,
      ServerCapability: 'semanticTokensDeltaProvider' as const,
      Direction: 'clientToServer' as const
    },
    SemanticTokensRange: {
      Method: 'textDocument/semanticTokens/range' as const,
      ServerCapability: 'semanticTokensRangeProvider' as const,
      Direction: 'clientToServer' as const
    },
    TypeDefinition: {
      Method: 'textDocument/typeDefinition' as const,
      ServerCapability: 'typeDefinitionProvider' as const,
      Direction: 'clientToServer' as const
    },
    TypeHierarchyPrepare: {
      Method: 'textDocument/prepareTypeHierarchy' as const,
      ServerCapability: 'typeHierarchyPrepareProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  CallHierarchy: {
    CallHierarchyIncomingCalls: {
      Method: 'callHierarchy/incomingCalls' as const,
      ServerCapability: 'callHierarchyIncomingCallsProvider' as const,
      Direction: 'clientToServer' as const
    },
    CallHierarchyOutgoingCalls: {
      Method: 'callHierarchy/outgoingCalls' as const,
      ServerCapability: 'callHierarchyOutgoingCallsProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  Workspace: {
    Configuration: {
      Method: 'workspace/configuration' as const,
      ServerCapability: 'configurationProvider' as const,
      Direction: 'serverToClient' as const
    },
    WorkspaceSymbol: {
      Method: 'workspace/symbol' as const,
      ServerCapability: 'workspaceSymbolProvider' as const,
      Direction: 'clientToServer' as const
    },
    ExecuteCommand: {
      Method: 'workspace/executeCommand' as const,
      ServerCapability: 'executeCommandProvider' as const,
      Direction: 'clientToServer' as const
    },
    ApplyWorkspaceEdit: {
      Method: 'workspace/applyEdit' as const,
      ServerCapability: 'applyWorkspaceEditProvider' as const,
      Direction: 'serverToClient' as const
    },
    WorkspaceDiagnostic: {
      Method: 'workspace/diagnostic' as const,
      ServerCapability: 'workspaceDiagnosticProvider' as const,
      Direction: 'clientToServer' as const
    },
    WillCreateFiles: {
      Method: 'workspace/willCreateFiles' as const,
      ServerCapability: 'willCreateFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    WillRenameFiles: {
      Method: 'workspace/willRenameFiles' as const,
      ServerCapability: 'willRenameFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    WillDeleteFiles: {
      Method: 'workspace/willDeleteFiles' as const,
      ServerCapability: 'willDeleteFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    WorkspaceFolders: {
      Method: 'workspace/workspaceFolders' as const,
      ServerCapability: 'workspaceFoldersProvider' as const,
      Direction: 'serverToClient' as const
    }
  },
  Client: {
    Registration: {
      Method: 'client/registerCapability' as const,
      ServerCapability: 'registrationProvider' as const,
      Direction: 'serverToClient' as const
    },
    Unregistration: {
      Method: 'client/unregisterCapability' as const,
      ServerCapability: 'unregistrationProvider' as const,
      Direction: 'serverToClient' as const
    }
  },
  General: {
    Initialize: {
      Method: 'initialize' as const,
      ServerCapability: 'initializeProvider' as const,
      Direction: 'clientToServer' as const
    },
    Shutdown: {
      Method: 'shutdown' as const,
      ServerCapability: 'shutdownProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  Window: {
    ShowMessageRequest: {
      Method: 'window/showMessageRequest' as const,
      ServerCapability: 'showMessageProvider' as const,
      Direction: 'serverToClient' as const
    },
    WorkDoneProgressCreate: {
      Method: 'window/workDoneProgress/create' as const,
      ServerCapability: 'workDoneProgressCreateProvider' as const,
      Direction: 'serverToClient' as const
    },
    ShowDocument: {
      Method: 'window/showDocument' as const,
      ServerCapability: 'showDocumentProvider' as const,
      Direction: 'serverToClient' as const
    }
  },
  CompletionItem: {
    CompletionResolve: {
      Method: 'completionItem/resolve' as const,
      ServerCapability: 'completionResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  CodeAction: {
    CodeActionResolve: {
      Method: 'codeAction/resolve' as const,
      ServerCapability: 'codeActionResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  WorkspaceSymbol: {
    WorkspaceSymbolResolve: {
      Method: 'workspaceSymbol/resolve' as const,
      ServerCapability: 'workspaceSymbolResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  CodeLens: {
    CodeLensResolve: {
      Method: 'codeLens/resolve' as const,
      ServerCapability: 'codeLensResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  DocumentLink: {
    DocumentLinkResolve: {
      Method: 'documentLink/resolve' as const,
      ServerCapability: 'documentLinkResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  InlayHint: {
    InlayHintResolve: {
      Method: 'inlayHint/resolve' as const,
      ServerCapability: 'inlayHintResolveProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  TypeHierarchy: {
    TypeHierarchySupertypes: {
      Method: 'typeHierarchy/supertypes' as const,
      ServerCapability: 'typeHierarchySupertypesProvider' as const,
      Direction: 'clientToServer' as const
    },
    TypeHierarchySubtypes: {
      Method: 'typeHierarchy/subtypes' as const,
      ServerCapability: 'typeHierarchySubtypesProvider' as const,
      Direction: 'clientToServer' as const
    }
  }
} as const;

export const LSPNotification = {
  General: {
    Initialized: {
      Method: 'initialized' as const,
      ServerCapability: 'initializedProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  Workspace: {
    DidChangeConfiguration: {
      Method: 'workspace/didChangeConfiguration' as const,
      ServerCapability: 'didChangeConfigurationProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidChangeWatchedFiles: {
      Method: 'workspace/didChangeWatchedFiles' as const,
      ServerCapability: 'didChangeWatchedFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidCreateFiles: {
      Method: 'workspace/didCreateFiles' as const,
      ServerCapability: 'didCreateFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidRenameFiles: {
      Method: 'workspace/didRenameFiles' as const,
      ServerCapability: 'didRenameFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidDeleteFiles: {
      Method: 'workspace/didDeleteFiles' as const,
      ServerCapability: 'didDeleteFilesProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidChangeWorkspaceFolders: {
      Method: 'workspace/didChangeWorkspaceFolders' as const,
      ServerCapability: 'didChangeWorkspaceFoldersProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  Window: {
    ShowMessage: {
      Method: 'window/showMessage' as const,
      ServerCapability: 'showMessageProvider' as const,
      Direction: 'serverToClient' as const
    },
    LogMessage: {
      Method: 'window/logMessage' as const,
      ServerCapability: 'logMessageProvider' as const,
      Direction: 'serverToClient' as const
    },
    WorkDoneProgressCancel: {
      Method: 'window/workDoneProgress/cancel' as const,
      ServerCapability: 'workDoneProgressCancelProvider' as const,
      Direction: 'clientToServer' as const
    }
  },
  Telemetry: {
    TelemetryEvent: {
      Method: 'telemetry/event' as const,
      ServerCapability: 'telemetryEventProvider' as const,
      Direction: 'serverToClient' as const
    }
  },
  TextDocument: {
    DidOpenTextDocument: {
      Method: 'textDocument/didOpen' as const,
      ServerCapability: 'didOpenTextDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidChangeTextDocument: {
      Method: 'textDocument/didChange' as const,
      ServerCapability: 'didChangeTextDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidCloseTextDocument: {
      Method: 'textDocument/didClose' as const,
      ServerCapability: 'didCloseTextDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidSaveTextDocument: {
      Method: 'textDocument/didSave' as const,
      ServerCapability: 'didSaveTextDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    WillSaveTextDocument: {
      Method: 'textDocument/willSave' as const,
      ServerCapability: 'willSaveTextDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    PublishDiagnostics: {
      Method: 'textDocument/publishDiagnostics' as const,
      ServerCapability: 'publishDiagnosticsProvider' as const,
      Direction: 'serverToClient' as const
    }
  },
  NotebookDocument: {
    DidOpenNotebookDocument: {
      Method: 'notebookDocument/didOpen' as const,
      ServerCapability: 'didOpenNotebookDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidChangeNotebookDocument: {
      Method: 'notebookDocument/didChange' as const,
      ServerCapability: 'didChangeNotebookDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidSaveNotebookDocument: {
      Method: 'notebookDocument/didSave' as const,
      ServerCapability: 'didSaveNotebookDocumentProvider' as const,
      Direction: 'clientToServer' as const
    },
    DidCloseNotebookDocument: {
      Method: 'notebookDocument/didClose' as const,
      ServerCapability: 'didCloseNotebookDocumentProvider' as const,
      Direction: 'clientToServer' as const
    }
  }
} as const;
