/**
 * Re-export LSP protocol types from vscode-languageserver-protocol
 * Auto-generated by scripts/generate-protocol-types.ts
 *
 * DO NOT EDIT MANUALLY - regenerate using: pnpm run generate:protocol
 */

import { LiteralUnion, OverrideProperties } from 'type-fest';

// ============================================================================
// Enums for LSP Kind Types
// ============================================================================

export enum SemanticTokenTypes {
  namespace = 'namespace',
  type = 'type',
  class = 'class',
  enum = 'enum',
  interface = 'interface',
  struct = 'struct',
  typeParameter = 'typeParameter',
  parameter = 'parameter',
  variable = 'variable',
  property = 'property',
  enumMember = 'enumMember',
  event = 'event',
  function = 'function',
  method = 'method',
  macro = 'macro',
  keyword = 'keyword',
  modifier = 'modifier',
  comment = 'comment',
  string = 'string',
  number = 'number',
  regexp = 'regexp',
  operator = 'operator',
  decorator = 'decorator'
}

export enum SemanticTokenModifiers {
  declaration = 'declaration',
  definition = 'definition',
  readonly = 'readonly',
  static = 'static',
  deprecated = 'deprecated',
  abstract = 'abstract',
  async = 'async',
  modification = 'modification',
  documentation = 'documentation',
  defaultLibrary = 'defaultLibrary'
}

/**
 * Known error codes for an `InitializeErrorCodes`;
 */
export enum InitializeErrorCodes {
  unknownProtocolVersion = 1
}

/**
 * The message type
 */
export enum MessageType {
  Error = 1,
  Warning = 2,
  Info = 3,
  Log = 4,
  Debug = 5
}

/**
 * Defines how the host (editor) should sync
document changes to the language server.
 */
export enum TextDocumentSyncKind {
  None = 0,
  Full = 1,
  Incremental = 2
}

/**
 * Represents reasons why a text document is saved.
 */
export enum TextDocumentSaveReason {
  Manual = 1,
  AfterDelay = 2,
  FocusOut = 3
}

/**
 * The file event type
 */
export enum FileChangeType {
  Created = 1,
  Changed = 2,
  Deleted = 3
}

export enum WatchKind {
  Create = 1,
  Change = 2,
  Delete = 4
}

/**
 * How a completion was triggered
 */
export enum CompletionTriggerKind {
  Invoked = 1,
  TriggerCharacter = 2,
  TriggerForIncompleteCompletions = 3
}

/**
 * How a signature help was triggered.
 */
export enum SignatureHelpTriggerKind {
  Invoked = 1,
  TriggerCharacter = 2,
  ContentChange = 3
}

export enum PrepareSupportDefaultBehavior {
  Identifier = 1
}

export enum integer {
  MAX_VALUE = 2147483647
}

export enum uinteger {
  MIN_VALUE = 0,
  MAX_VALUE = 2147483647
}

/**
 * A set of predefined range kinds.
 */
export enum FoldingRangeKind {
  Comment = 'comment',
  Imports = 'imports',
  Region = 'region'
}

/**
 * Token format for semantic tokens.
 * @since 3.16.0
 */
export enum TokenFormat {
  Relative = 'relative'
}

/**
 * The diagnostic's severity.
 */
export enum DiagnosticSeverity {
  Error = 1,
  Warning = 2,
  Information = 3,
  Hint = 4
}

/**
 * The diagnostic tags.
 */
export enum DiagnosticTag {
  Unnecessary = 1,
  Deprecated = 2
}

/**
 * Describes the content type that a client supports in various
result literals like `Hover`, `ParameterInfo` or `CompletionItem`.

Please note that `MarkupKinds` must not start with a `$`. This kinds
are reserved for internal usage.
 */
export enum MarkupKind {
  PlainText = 'plaintext',
  Markdown = 'markdown'
}

/**
 * The kind of a completion entry.
 */
export enum CompletionItemKind {
  Text = 1,
  Method = 2,
  Function = 3,
  Constructor = 4,
  Field = 5,
  Variable = 6,
  Class = 7,
  Interface = 8,
  Module = 9,
  Property = 10,
  Unit = 11,
  Value = 12,
  Enum = 13,
  Keyword = 14,
  Snippet = 15,
  Color = 16,
  File = 17,
  Reference = 18,
  Folder = 19,
  EnumMember = 20,
  Constant = 21,
  Struct = 22,
  Event = 23,
  Operator = 24,
  TypeParameter = 25
}

/**
 * Defines whether the insert text in a completion item should be interpreted as
plain text or a snippet.
 */
export enum InsertTextFormat {
  PlainText = 1,
  Snippet = 2
}

/**
 * Completion item tags are extra annotations that tweak the rendering of a completion
item.
 */
export enum CompletionItemTag {
  Deprecated = 1
}

/**
 * How whitespace and indentation is handled during completion
item insertion.
 */
export enum InsertTextMode {
  asIs = 1,
  adjustIndentation = 2
}

/**
 * A document highlight kind.
 */
export enum DocumentHighlightKind {
  Text = 1,
  Read = 2,
  Write = 3
}

/**
 * A symbol kind.
 */
export enum SymbolKind {
  File = 1,
  Module = 2,
  Namespace = 3,
  Package = 4,
  Class = 5,
  Method = 6,
  Property = 7,
  Field = 8,
  Constructor = 9,
  Enum = 10,
  Interface = 11,
  Function = 12,
  Variable = 13,
  Constant = 14,
  String = 15,
  Number = 16,
  Boolean = 17,
  Array = 18,
  Object = 19,
  Key = 20,
  Null = 21,
  EnumMember = 22,
  Struct = 23,
  Event = 24,
  Operator = 25,
  TypeParameter = 26
}

/**
 * Symbol tags are extra annotations that tweak the rendering of a symbol.
 */
export enum SymbolTag {
  Deprecated = 1
}

/**
 * A set of predefined code action kinds
 */
export enum CodeActionKind {
  Empty = '',
  QuickFix = 'quickfix',
  Refactor = 'refactor',
  RefactorExtract = 'refactor.extract',
  RefactorInline = 'refactor.inline',
  RefactorRewrite = 'refactor.rewrite',
  Source = 'source',
  SourceOrganizeImports = 'source.organizeImports',
  SourceFixAll = 'source.fixAll'
}

/**
 * The reason why code actions were requested.
 */
export enum CodeActionTriggerKind {
  Invoked = 1,
  Automatic = 2
}

/**
 * Inlay hint kinds.
 */
export enum InlayHintKind {
  Type = 1,
  Parameter = 2
}

/**
 * Describes how an {@link InlineCompletionItemProvider inline completion provider} was triggered.
 */
export enum InlineCompletionTriggerKind {
  Invoked = 0,
  Automatic = 1
}

// ============================================================================
// Import types that need overrides
// ============================================================================

import type {
  FoldingRange as FoldingRangeBase,
  FoldingRangeClientCapabilities as FoldingRangeClientCapabilitiesBase,
  CodeAction as CodeActionBase,
  CodeActionClientCapabilities as CodeActionClientCapabilitiesBase
} from 'vscode-languageserver-protocol';

// ============================================================================
// Type Overrides for Extensible String-Based Kinds
// ============================================================================

/**
 * FoldingRange with enhanced type support for extensible string-based kinds
 */
export type FoldingRange = OverrideProperties<
  FoldingRangeBase,
  {
    kind?: LiteralUnion<FoldingRangeKind, string>;
  }
>;

/**
 * FoldingRangeClientCapabilities with enhanced type support for extensible string-based kinds
 */
export type FoldingRangeClientCapabilities = OverrideProperties<
  FoldingRangeClientCapabilitiesBase,
  {
    foldingRangeKind?: {
      valueSet: Array<LiteralUnion<FoldingRangeKind, string>>;
    };
  }
>;

/**
 * CodeAction with enhanced type support for extensible string-based kinds
 */
export type CodeAction = OverrideProperties<
  CodeActionBase,
  {
    kind?: LiteralUnion<CodeActionKind, string>;
  }
>;

/**
 * CodeActionClientCapabilities with enhanced type support for extensible string-based kinds
 */
export type CodeActionClientCapabilities = OverrideProperties<
  CodeActionClientCapabilitiesBase,
  {
    codeActionLiteralSupport?: {
      codeActionKind?: {
        valueSet: Array<LiteralUnion<CodeActionKind, string>>;
      };
    };
  }
>;

// ============================================================================
// Re-export Protocol Types (categorized by LSP features)
// ============================================================================

// Core Types
export type {
  CallHierarchyItem,
  CodeLens,
  ColorInformation,
  ColorPresentation,
  Command,
  CompletionItem,
  CompletionList,
  Definition,
  Diagnostic,
  DocumentDiagnosticReport,
  DocumentHighlight,
  DocumentLink,
  DocumentSymbol,
  DocumentUri,
  Hover,
  InlayHint,
  InlineValue,
  LSPAny,
  LSPArray,
  LSPObject,
  Location,
  LocationLink,
  MarkupContent,
  Position,
  Range,
  SelectionRange,
  SemanticTokens,
  SignatureHelp,
  SymbolInformation,
  TextDocument,
  TextDocumentIdentifier,
  TextDocumentItem,
  TextEdit,
  URI,
  VersionedTextDocumentIdentifier,
  WorkspaceDiagnosticReport,
  WorkspaceEdit,
  WorkspaceSymbol
} from 'vscode-languageserver-protocol';

// Apply Workspace Edit
export type {
  ApplyWorkspaceEditParams,
  ApplyWorkspaceEditResponse,
  ApplyWorkspaceEditResult
} from 'vscode-languageserver-protocol';

// Call Hierarchy Incoming Calls
export type { CallHierarchyIncomingCallsParams } from 'vscode-languageserver-protocol';

// Call Hierarchy Outgoing Calls
export type { CallHierarchyOutgoingCallsParams } from 'vscode-languageserver-protocol';

// Call Hierarchy Prepare
export type { CallHierarchyPrepareParams } from 'vscode-languageserver-protocol';

// Code Action
export type {
  CodeActionContext,
  CodeActionOptions,
  CodeActionParams,
  CodeActionRegistrationOptions
} from 'vscode-languageserver-protocol';

// Code Lens
export type {
  CodeLensClientCapabilities,
  CodeLensOptions,
  CodeLensParams,
  CodeLensRegistrationOptions,
  CodeLensWorkspaceClientCapabilities
} from 'vscode-languageserver-protocol';

// Color Presentation
export type { ColorPresentationParams } from 'vscode-languageserver-protocol';

// Completion
export type {
  CompletionClientCapabilities,
  CompletionContext,
  CompletionItemLabelDetails,
  CompletionOptions,
  CompletionParams,
  CompletionRegistrationOptions
} from 'vscode-languageserver-protocol';

// Configuration
export type { ConfigurationItem, ConfigurationParams } from 'vscode-languageserver-protocol';

// Declaration
export type {
  Declaration,
  DeclarationClientCapabilities,
  DeclarationLink,
  DeclarationOptions,
  DeclarationParams,
  DeclarationRegistrationOptions
} from 'vscode-languageserver-protocol';

// Definition
export type {
  DefinitionClientCapabilities,
  DefinitionLink,
  DefinitionOptions,
  DefinitionParams,
  DefinitionRegistrationOptions
} from 'vscode-languageserver-protocol';

// Did Change Configuration
export type {
  DidChangeConfigurationClientCapabilities,
  DidChangeConfigurationParams,
  DidChangeConfigurationRegistrationOptions
} from 'vscode-languageserver-protocol';

// Did Change Notebook Document
export type { DidChangeNotebookDocumentParams } from 'vscode-languageserver-protocol';

// Did Change Text Document
export type { DidChangeTextDocumentParams } from 'vscode-languageserver-protocol';

// Did Change Watched Files
export type {
  DidChangeWatchedFilesClientCapabilities,
  DidChangeWatchedFilesParams,
  DidChangeWatchedFilesRegistrationOptions
} from 'vscode-languageserver-protocol';

// Did Change Workspace Folders
export type { DidChangeWorkspaceFoldersParams } from 'vscode-languageserver-protocol';

// Did Close Notebook Document
export type { DidCloseNotebookDocumentParams } from 'vscode-languageserver-protocol';

// Did Close Text Document
export type { DidCloseTextDocumentParams } from 'vscode-languageserver-protocol';

// Did Open Notebook Document
export type { DidOpenNotebookDocumentParams } from 'vscode-languageserver-protocol';

// Did Open Text Document
export type { DidOpenTextDocumentParams } from 'vscode-languageserver-protocol';

// Did Save Notebook Document
export type { DidSaveNotebookDocumentParams } from 'vscode-languageserver-protocol';

// Did Save Text Document
export type { DidSaveTextDocumentParams } from 'vscode-languageserver-protocol';

// Document Color
export type {
  DocumentColorOptions,
  DocumentColorParams,
  DocumentColorRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document Diagnostic
export type {
  DocumentDiagnosticParams,
  DocumentDiagnosticReportKind,
  DocumentDiagnosticReportPartialResult
} from 'vscode-languageserver-protocol';

// Document Formatting
export type {
  DocumentFormattingClientCapabilities,
  DocumentFormattingOptions,
  DocumentFormattingParams,
  DocumentFormattingRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document Highlight
export type {
  DocumentHighlightClientCapabilities,
  DocumentHighlightOptions,
  DocumentHighlightParams,
  DocumentHighlightRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document Link
export type {
  DocumentLinkClientCapabilities,
  DocumentLinkOptions,
  DocumentLinkParams,
  DocumentLinkRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document On Type Formatting
export type {
  DocumentOnTypeFormattingClientCapabilities,
  DocumentOnTypeFormattingOptions,
  DocumentOnTypeFormattingParams,
  DocumentOnTypeFormattingRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document Range Formatting
export type {
  DocumentRangeFormattingClientCapabilities,
  DocumentRangeFormattingOptions,
  DocumentRangeFormattingParams,
  DocumentRangeFormattingRegistrationOptions
} from 'vscode-languageserver-protocol';

// Document Ranges Formatting
export type { DocumentRangesFormattingParams } from 'vscode-languageserver-protocol';

// Document Symbol
export type {
  DocumentSymbolClientCapabilities,
  DocumentSymbolOptions,
  DocumentSymbolParams,
  DocumentSymbolRegistrationOptions
} from 'vscode-languageserver-protocol';

// Execute Command
export type {
  ExecuteCommandClientCapabilities,
  ExecuteCommandOptions,
  ExecuteCommandParams,
  ExecuteCommandRegistrationOptions
} from 'vscode-languageserver-protocol';

// Folding Range
export type {
  FoldingRangeOptions,
  FoldingRangeParams,
  FoldingRangeProviderOptions,
  FoldingRangeRegistrationOptions
} from 'vscode-languageserver-protocol';

// Hover
export type {
  HoverClientCapabilities,
  HoverOptions,
  HoverParams,
  HoverRegistrationOptions
} from 'vscode-languageserver-protocol';

// Implementation
export type {
  ImplementationOptions,
  ImplementationParams,
  ImplementationRegistrationOptions
} from 'vscode-languageserver-protocol';

// Initialize
export type {
  InitializeError,
  InitializeParams,
  InitializeResult,
  InitializedParams
} from 'vscode-languageserver-protocol';

// Inlay Hint
export type {
  InlayHintClientCapabilities,
  InlayHintLabelPart,
  InlayHintOptions,
  InlayHintParams,
  InlayHintRegistrationOptions,
  InlayHintWorkspaceClientCapabilities
} from 'vscode-languageserver-protocol';

// Inline Completion
export type {
  InlineCompletionClientCapabilities,
  InlineCompletionContext,
  InlineCompletionItem,
  InlineCompletionList,
  InlineCompletionOptions,
  InlineCompletionParams,
  InlineCompletionRegistrationOptions
} from 'vscode-languageserver-protocol';

// Inline Value
export type {
  InlineValueClientCapabilities,
  InlineValueContext,
  InlineValueEvaluatableExpression,
  InlineValueOptions,
  InlineValueParams,
  InlineValueRegistrationOptions,
  InlineValueText,
  InlineValueVariableLookup,
  InlineValueWorkspaceClientCapabilities
} from 'vscode-languageserver-protocol';

// Linked Editing Range
export type {
  LinkedEditingRangeClientCapabilities,
  LinkedEditingRangeOptions,
  LinkedEditingRangeParams,
  LinkedEditingRangeRegistrationOptions,
  LinkedEditingRanges
} from 'vscode-languageserver-protocol';

// Log Message
export type { LogMessageParams } from 'vscode-languageserver-protocol';

// Moniker
export type {
  Moniker,
  MonikerClientCapabilities,
  MonikerKind,
  MonikerOptions,
  MonikerParams,
  MonikerRegistrationOptions
} from 'vscode-languageserver-protocol';

// Prepare Rename
export type { PrepareRenameParams, PrepareRenameResult } from 'vscode-languageserver-protocol';

// Publish Diagnostics
export type {
  PublishDiagnosticsClientCapabilities,
  PublishDiagnosticsParams
} from 'vscode-languageserver-protocol';

// Registration
export type { Registration, RegistrationParams } from 'vscode-languageserver-protocol';

// Rename
export type {
  RenameClientCapabilities,
  RenameFile,
  RenameFileOptions,
  RenameFilesParams,
  RenameOptions,
  RenameParams,
  RenameRegistrationOptions
} from 'vscode-languageserver-protocol';

// Selection Range
export type {
  SelectionRangeClientCapabilities,
  SelectionRangeOptions,
  SelectionRangeParams,
  SelectionRangeProviderOptions,
  SelectionRangeRegistrationOptions
} from 'vscode-languageserver-protocol';

// Semantic Tokens
export type {
  SemanticTokensClientCapabilities,
  SemanticTokensDelta,
  SemanticTokensDeltaParams,
  SemanticTokensDeltaPartialResult,
  SemanticTokensEdit,
  SemanticTokensLegend,
  SemanticTokensOptions,
  SemanticTokensParams,
  SemanticTokensPartialResult,
  SemanticTokensRangeParams,
  SemanticTokensRegistrationOptions
} from 'vscode-languageserver-protocol';

// Show Document
export type {
  ShowDocumentClientCapabilities,
  ShowDocumentParams,
  ShowDocumentResult
} from 'vscode-languageserver-protocol';

// Show Message
export type {
  ShowMessageParams,
  ShowMessageRequestClientCapabilities,
  ShowMessageRequestParams
} from 'vscode-languageserver-protocol';

// Signature Help
export type {
  SignatureHelpClientCapabilities,
  SignatureHelpContext,
  SignatureHelpOptions,
  SignatureHelpParams,
  SignatureHelpRegistrationOptions
} from 'vscode-languageserver-protocol';

// Type Definition
export type {
  TypeDefinitionOptions,
  TypeDefinitionParams,
  TypeDefinitionRegistrationOptions
} from 'vscode-languageserver-protocol';

// Type Hierarchy Prepare
export type { TypeHierarchyPrepareParams } from 'vscode-languageserver-protocol';

// Type Hierarchy Subtypes
export type { TypeHierarchySubtypesParams } from 'vscode-languageserver-protocol';

// Type Hierarchy Supertypes
export type { TypeHierarchySupertypesParams } from 'vscode-languageserver-protocol';

// Unregistration
export type { Unregistration, UnregistrationParams } from 'vscode-languageserver-protocol';

// Will Save Text Document
export type { WillSaveTextDocumentParams } from 'vscode-languageserver-protocol';

// Work Done Progress Cancel
export type { WorkDoneProgressCancelParams } from 'vscode-languageserver-protocol';

// Work Done Progress Create
export type { WorkDoneProgressCreateParams } from 'vscode-languageserver-protocol';

// Workspace Diagnostic
export type {
  WorkspaceDiagnosticParams,
  WorkspaceDiagnosticReportPartialResult
} from 'vscode-languageserver-protocol';

// Workspace Folders
export type { WorkspaceFoldersChangeEvent } from 'vscode-languageserver-protocol';

// Workspace Symbol
export type {
  WorkspaceSymbolClientCapabilities,
  WorkspaceSymbolOptions,
  WorkspaceSymbolParams,
  WorkspaceSymbolRegistrationOptions
} from 'vscode-languageserver-protocol';

// Other Types
export type {
  AnnotatedTextEdit,
  BaseSymbolInformation,
  CallHierarchyClientCapabilities,
  CallHierarchyIncomingCall,
  CallHierarchyOptions,
  CallHierarchyOutgoingCall,
  CallHierarchyRegistrationOptions,
  ChangeAnnotation,
  ChangeAnnotationIdentifier,
  ClientCapabilities,
  CodeDescription,
  Color,
  ColorOptions,
  ColorProviderOptions,
  ColorRegistrationOptions,
  CreateFile,
  CreateFileOptions,
  CreateFilesParams,
  DeleteFile,
  DeleteFileOptions,
  DeleteFilesParams,
  DiagnosticClientCapabilities,
  DiagnosticOptions,
  DiagnosticRegistrationOptions,
  DiagnosticRelatedInformation,
  DiagnosticServerCancellationData,
  DocumentFilter,
  DocumentSelector,
  ExecutionSummary,
  FailureHandlingKind,
  FileCreate,
  FileDelete,
  FileEvent,
  FileOperationClientCapabilities,
  FileOperationOptions,
  FileOperationPatternKind,
  FileOperationPatternOptions,
  FileOperationRegistrationOptions,
  FileRename,
  FileSystemWatcher,
  FormattingOptions,
  FullDocumentDiagnosticReport,
  GeneralClientCapabilities,
  GlobPattern,
  InsertReplaceEdit,
  MarkdownClientCapabilities,
  MarkedString,
  MessageActionItem,
  NotebookCell,
  NotebookCellArrayChange,
  NotebookCellKind,
  NotebookCellTextDocumentFilter,
  NotebookDocument,
  NotebookDocumentChangeEvent,
  NotebookDocumentClientCapabilities,
  NotebookDocumentFilter,
  NotebookDocumentIdentifier,
  NotebookDocumentSyncClientCapabilities,
  NotebookDocumentSyncOptions,
  NotebookDocumentSyncRegistrationOptions,
  OptionalVersionedTextDocumentIdentifier,
  ParameterInformation,
  PartialResultParams,
  Pattern,
  PositionEncodingKind,
  PreviousResultId,
  ReferenceClientCapabilities,
  ReferenceContext,
  ReferenceOptions,
  ReferenceParams,
  ReferenceRegistrationOptions,
  RegularExpressionsClientCapabilities,
  RelatedFullDocumentDiagnosticReport,
  RelatedUnchangedDocumentDiagnosticReport,
  RelativePattern,
  ResourceOperationKind,
  SaveOptions,
  ServerCapabilities,
  SignatureInformation,
  StaticRegistrationOptions,
  TextDocumentChangeRegistrationOptions,
  TextDocumentClientCapabilities,
  TextDocumentContentChangeEvent,
  TextDocumentEdit,
  TextDocumentFilter,
  TextDocumentPositionParams,
  TextDocumentRegistrationOptions,
  TextDocumentSaveRegistrationOptions,
  TextDocumentSyncClientCapabilities,
  TextDocumentSyncOptions,
  TextEditChange,
  TypeHierarchyClientCapabilities,
  TypeHierarchyItem,
  TypeHierarchyOptions,
  TypeHierarchyRegistrationOptions,
  UnchangedDocumentDiagnosticReport,
  UniquenessLevel,
  VersionedNotebookDocumentIdentifier,
  WindowClientCapabilities,
  WorkDoneProgressBegin,
  WorkDoneProgressEnd,
  WorkDoneProgressOptions,
  WorkDoneProgressParams,
  WorkDoneProgressReport,
  WorkspaceClientCapabilities,
  WorkspaceDocumentDiagnosticReport,
  WorkspaceEditClientCapabilities,
  WorkspaceFolder,
  WorkspaceFullDocumentDiagnosticReport,
  WorkspaceUnchangedDocumentDiagnosticReport,
  _InitializeParams,
  decimal
} from 'vscode-languageserver-protocol';
