// This module is deliberately zod-free, and `startup-purity.test.ts` enforces
// it: everything schema-derived is precomputed into ./generated by
// scripts/generate-cli-descriptors.ts, and the schemas that validate a server's
// response are loaded by a dynamic import in the action handler below.
import { Command, Option } from 'commander';
import { pathToFileURL } from 'node:url';

import { parseLineCol, toLspPosition, resolvePathArg } from './io.js';
import type { GlobalFlags } from './io.js';
import { assessResultQuality } from './result-quality.js';
import type { RefactorSession } from './session.js';
import {
  applyWorkspaceEdit,
  planWorkspaceEdit,
  type WorkspaceEdit,
  type LspTextEdit,
  type AppliedChange,
  type BoundaryGuard
} from './apply.js';
import type {
  ArgPattern,
  FieldDescriptor,
  MethodDescriptor
} from './generated/command-descriptors.js';

export type { ArgPattern, FieldDescriptor, MethodDescriptor };

function toCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Register the Commander option for one generated field descriptor.
 *
 * Note the asymmetry around choices: a scalar ARRAY lists its valid values in
 * the description rather than via Commander `.choices()`, because the value
 * arrives comma-joined (`--code-action-only quickfix,refactor`) and would fail
 * choice validation as a whole string.
 */
function addFieldOptions(cmd: Command, field: FieldDescriptor): void {
  if (field.isArray) {
    const desc = field.choices
      ? `${field.cliKey} — comma-separated (${field.choices.join('|')})`
      : `${field.cliKey} (comma-separated)`;
    cmd.addOption(new Option(`--${field.cliKey} <items>`, desc));
    return;
  }
  if (field.choices) {
    cmd.addOption(
      new Option(`--${field.cliKey} <value>`, field.cliKey).choices([...field.choices])
    );
    return;
  }
  cmd.option(`--${field.cliKey} <value>`, field.cliKey);
}

/**
 * Read back the option registered for one field descriptor. Returns `undefined`
 * when the flag was not supplied. Scalar arrays arrive comma-separated and are
 * split here; every item is JSON-parsed opportunistically so numeric and
 * boolean values survive as themselves.
 */
export function extractFieldValue(opts: Record<string, unknown>, field: FieldDescriptor): unknown {
  const raw = opts[toCamelCase(field.cliKey)];
  if (raw === undefined) return undefined;
  if (field.isArray && typeof raw === 'string') {
    return raw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map((item) => {
        try {
          return JSON.parse(item);
        } catch {
          return item;
        }
      });
  }
  if (typeof raw === 'string') {
    try {
      return JSON.parse(raw);
    } catch {
      return raw;
    }
  }
  return raw;
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * Deep-merge `src` into `dst`: nested objects merge recursively; arrays and
 * scalars replace. Used to layer `--params` over the positional/flag-derived
 * base so a caller can pass only the residual JSON (e.g. codeAction's
 * `context.diagnostics`) without clobbering `textDocument`/`range`/flag fields.
 */
const UNSAFE_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

export function deepMergeInto(
  dst: Record<string, unknown>,
  src: Record<string, unknown>
): Record<string, unknown> {
  for (const [k, v] of Object.entries(src)) {
    if (UNSAFE_KEYS.has(k)) continue;
    const cur = dst[k];
    if (isPlainObject(cur) && isPlainObject(v)) deepMergeInto(cur, v);
    else dst[k] = v;
  }
  return dst;
}

/**
 * Write `value` at `dottedPath` in `target`, creating intermediate objects.
 * Mirrors the nesting the old recursive `extractFieldValue` rebuilt implicitly:
 * a descriptor's `paramsPath` of `context.only` lands at `params.context.only`
 * without disturbing a sibling `context.diagnostics` supplied via `--params`.
 * Prototype-polluting segments are refused at every level, matching
 * `deepMergeInto`.
 */
export function setAtPath(
  target: Record<string, unknown>,
  dottedPath: string,
  value: unknown
): void {
  const parts = dottedPath.split('.');
  let cur = target;
  for (const part of parts.slice(0, -1)) {
    if (UNSAFE_KEYS.has(part)) return;
    if (!isPlainObject(cur[part])) cur[part] = {};
    cur = cur[part] as Record<string, unknown>;
  }
  const last = parts.at(-1)!;
  if (UNSAFE_KEYS.has(last)) return;
  if (isPlainObject(cur[last]) && isPlainObject(value)) deepMergeInto(cur[last], value);
  else cur[last] = value;
}

export function marshalParams(
  pattern: ArgPattern,
  positional: string[],
  opts: Record<string, unknown>,
  flags: GlobalFlags,
  anchorFile?: string
): unknown {
  const effective =
    anchorFile !== undefined && pattern !== 'query' && pattern !== 'raw'
      ? [anchorFile, ...positional]
      : positional;
  const override =
    typeof opts['params'] === 'string' ? (JSON.parse(opts['params']) as unknown) : undefined;

  switch (pattern) {
    case 'file-position-newname': {
      const file = resolvePathArg(effective[0]!, flags);
      const pos = parseLineCol(effective[1]!);
      return {
        textDocument: { uri: pathToFileURL(file).href },
        position: toLspPosition(pos),
        newName: effective[2]
      };
    }
    case 'file-position': {
      const file = resolvePathArg(effective[0]!, flags);
      const pos = parseLineCol(effective[1]!);
      return {
        textDocument: { uri: pathToFileURL(file).href },
        position: toLspPosition(pos)
      };
    }
    case 'file-range': {
      const file = resolvePathArg(effective[0]!, flags);
      const [startStr, endStr] = (effective[1] ?? '').split('-');
      const start = parseLineCol(startStr ?? '1:1');
      const end = parseLineCol(endStr ?? startStr ?? '1:1');
      return {
        textDocument: { uri: pathToFileURL(file).href },
        range: { start: toLspPosition(start), end: toLspPosition(end) }
      };
    }
    case 'file': {
      const file = resolvePathArg(effective[0]!, flags);
      return { textDocument: { uri: pathToFileURL(file).href } };
    }
    case 'query':
      return { query: positional[0] ?? '' };
    case 'raw':
      // No positional/flag surface — `--params` is the entire request body.
      if (override === undefined) throw new Error('This method requires --params <json>');
      return override;
  }
}

/**
 * Wrap a TextEdit[] result as a single-file WorkspaceEdit using the
 * `textDocument.uri` already present in the marshaled params. Returns null
 * when the params don't carry a recognizable URI (raw-pattern calls).
 */
function textEditsToWorkspaceEdit(edits: LspTextEdit[], params: unknown): WorkspaceEdit | null {
  if (typeof params !== 'object' || params === null) return null;
  const td = (params as Record<string, unknown>)['textDocument'];
  const uri = typeof td === 'object' && td !== null ? (td as Record<string, unknown>)['uri'] : null;
  if (typeof uri !== 'string') return null;
  return { changes: { [uri]: edits } };
}

export function printAppliedChanges(
  changes: AppliedChange[],
  method: string,
  dryRun: boolean,
  json: boolean
): void {
  if (json) {
    process.stdout.write(JSON.stringify({ ok: true, method, dryRun, changes }) + '\n');
  } else {
    const label = dryRun ? '[dry-run]' : '[applied]';
    for (const c of changes) {
      const detail =
        c.kind === 'rename'
          ? `${c.path} → ${c.toPath}`
          : c.kind === 'edit'
            ? `${c.path} (${c.editCount} edit${c.editCount !== 1 ? 's' : ''})`
            : c.path;
      process.stdout.write(`${label} ${c.kind} ${detail}\n`);
    }
  }
}

function injectRequiredDefaults(method: string, params: unknown): unknown {
  if (typeof params !== 'object' || params === null) return params;
  const p = params as Record<string, unknown>;
  if (method === 'textDocument/references' && !('context' in p)) {
    return { ...p, context: { includeDeclaration: true } };
  }
  if (method === 'textDocument/codeAction' && !('context' in p)) {
    return { ...p, context: { diagnostics: [] } };
  }
  if (
    (method === 'textDocument/formatting' || method === 'textDocument/rangeFormatting') &&
    !('options' in p)
  ) {
    return { ...p, options: { tabSize: 2, insertSpaces: true } };
  }
  return params;
}

export function zodToCommander(
  method: string,
  descriptor: MethodDescriptor,
  session: RefactorSession,
  flags: GlobalFlags,
  anchorFile?: string
): Command {
  const subcommand = method.split('/').slice(1).join('-') || method;
  const cmd = new Command(subcommand);
  const pattern = descriptor.pattern;
  const hasAnchor = anchorFile !== undefined;

  switch (pattern) {
    case 'file-position-newname':
      if (!hasAnchor) cmd.argument('<file>', 'file path (relative to --root)');
      cmd.argument('<line:col>', '1-based position, e.g. 12:7');
      cmd.argument('<newName>', 'new symbol name');
      break;
    case 'file-position':
      if (!hasAnchor) cmd.argument('<file>', 'file path (relative to --root)');
      cmd.argument('<line:col>', '1-based position, e.g. 12:7');
      break;
    case 'file-range':
      if (!hasAnchor) cmd.argument('<file>', 'file path (relative to --root)');
      cmd.argument('<range>', 'range as startLine:col-endLine:col, e.g. 2:1-4:5');
      break;
    case 'file':
      if (!hasAnchor) cmd.argument('<file>', 'file path (relative to --root)');
      break;
    case 'query':
      cmd.argument('<query>', 'search query string');
      break;
    case 'raw':
      break;
  }

  cmd.option(
    '--params <json>',
    'extra LSP params as JSON, deep-merged over positional args + flags (for raw methods, the full params)'
  );

  // Options for fields not covered by the positional pattern, precomputed at
  // build time by scripts/generate-cli-descriptors.ts. Nested objects were
  // already flattened into hyphenated cliKeys there.
  for (const field of descriptor.fields) addFieldOptions(cmd, field);

  cmd.action(async (...cmdArgs) => {
    // Commander passes (...declaredArgs, options, command): the Command instance
    // is LAST and the parsed options object is second-to-last. This previously
    // read `at(-1)` as the options — but that's the Command, so `--params` (and
    // every other option) never reached marshalParams. For raw-pattern methods
    // (e.g. workspace/willRenameFiles) that made `--params` look absent and threw
    // "requires --params". Read options off the Command via `.opts()`.
    const command = cmdArgs.at(-1) as { opts(): Record<string, unknown> };
    const cmdOpts = command.opts();
    const positional = cmdArgs.slice(0, -2).map(String);

    try {
      const rawParams = marshalParams(pattern, positional, cmdOpts, flags, anchorFile);

      // Layer inputs over the positional base, lowest → highest precedence:
      //   positionals (marshalParams) → flags → --params.
      // Object fields deep-merge so e.g. context.{only,triggerKind} (flags) and
      // context.diagnostics (--params) combine instead of clobbering.
      if (pattern !== 'raw' && typeof rawParams === 'object' && rawParams !== null) {
        const base = rawParams as Record<string, unknown>;
        for (const field of descriptor.fields) {
          const val = extractFieldValue(cmdOpts, field);
          if (val === undefined) continue;
          setAtPath(base, field.paramsPath, val);
        }
        // --params is a residual, deep-merged LAST over positionals + flags
        // (not a full override) so callers pass only the fields not surfaced as
        // args/flags. The option help and the drill-down example say so.
        if (typeof cmdOpts['params'] === 'string') {
          const override = JSON.parse(cmdOpts['params']) as unknown;
          if (isPlainObject(override)) deepMergeInto(base, override);
        }
      }

      const params = injectRequiredDefaults(method, rawParams);
      // Retry while the result is null OR looks incomplete (e.g. a
      // declaration-only `references` answer before the project finished
      // loading). assessResultQuality only flags references, so other methods
      // are unaffected; on timeout we keep the best-effort result and the
      // post-hoc warning below still fires.
      const result = await session.requestWithRetry(
        () =>
          (session.lsp.sendRequest as (method: string, params: unknown) => Promise<unknown>)(
            method,
            params
          ),
        (r) => assessResultQuality(method, params, r).partial
      );

      // Deferred deliberately: these validate the SERVER's response, so they
      // are only needed once a request has already completed. Importing them
      // here keeps zod (~15-30ms load + ~17ms schema construction) off the
      // startup path entirely — `--help` never issues a request and so never
      // pays it, and on a real dispatch the cost overlaps an LSP round-trip
      // the caller is already waiting on.
      const { NonEmptyWorkspaceEditSchema, TextEditArraySchema, CodeActionSchema } =
        await import('@lspeasy/core/schemas');

      // Collect workspace edits from up to four sources:
      // 1. Direct WorkspaceEdit result (e.g. textDocument/rename)
      // 2. TextEdit[] result (e.g. textDocument/formatting) — wrapped using the
      //    textDocument.uri already in rawParams
      // 3. CodeAction[].edit — inline edits embedded in code action results
      // 4. Server-pushed edits via workspace/applyEdit (e.g. workspace/executeCommand)
      const capturedEdits = session.takeCapturedEdits();
      const weResult = NonEmptyWorkspaceEditSchema.safeParse(result);
      const teResult = TextEditArraySchema.safeParse(result);
      // LSP allows codeAction results to be (Command | CodeAction)[]. Parse each
      // item individually so Command entries don't cause the whole parse to fail.
      const codeActionItems = Array.isArray(result)
        ? result.flatMap((item) => {
            const parsed = CodeActionSchema.safeParse(item);
            return parsed.success ? [parsed.data] : [];
          })
        : [];
      // Only auto-apply when exactly one code action carries an edit; if multiple
      // edit-bearing actions are returned, fall through to JSON printing so the
      // caller can choose rather than silently applying the wrong quick-fix.
      const inlineCodeActionEdits = codeActionItems
        .map((a) => a.edit)
        .filter((e) => e != null && NonEmptyWorkspaceEditSchema.safeParse(e).success);
      const inlineCodeActionEdit: WorkspaceEdit | null =
        inlineCodeActionEdits.length === 1
          ? (inlineCodeActionEdits[0] as unknown as WorkspaceEdit)
          : null;
      const directEdit: WorkspaceEdit | null = weResult.success
        ? (weResult.data as unknown as WorkspaceEdit)
        : teResult.success && teResult.data.length > 0
          ? textEditsToWorkspaceEdit(teResult.data, rawParams)
          : inlineCodeActionEdit;

      // For methods that produce edits (rename, formatting, codeAction), a null
      // result means the server could not fulfil the request — treat as an error.
      const isEditMethod =
        method === 'textDocument/rename' ||
        method === 'textDocument/formatting' ||
        method === 'textDocument/rangeFormatting' ||
        method === 'textDocument/codeAction';
      if (isEditMethod && result === null && capturedEdits.length === 0) {
        throw new Error(`${method} returned null — server could not fulfil the request`);
      }

      if (directEdit || capturedEdits.length > 0) {
        const guard: BoundaryGuard = {
          root: flags.root,
          allowOutsideRoot: flags.allowOutsideRoot
        };
        const allChanges: AppliedChange[] = [];
        const edits = directEdit ? [directEdit, ...capturedEdits] : capturedEdits;
        for (const edit of edits) {
          const changes = flags.dryRun
            ? planWorkspaceEdit(edit, guard)
            : applyWorkspaceEdit(edit, guard);
          allChanges.push(...changes);
        }
        printAppliedChanges(allChanges, method, flags.dryRun, flags.json);
      } else {
        const quality = assessResultQuality(method, params, result);
        if (flags.json) {
          process.stdout.write(
            JSON.stringify({
              ok: true,
              method,
              result,
              ...(quality.partial ? { partial: true, warning: quality.warning } : {})
            }) + '\n'
          );
        } else {
          process.stdout.write(JSON.stringify(result, null, 2) + '\n');
        }
        if (quality.partial && quality.warning) {
          process.stderr.write(`warning: ${quality.warning}\n`);
        }
      }
    } catch (err) {
      if (flags.json) {
        process.stdout.write(JSON.stringify({ ok: false, error: String(err) }) + '\n');
      } else {
        process.stderr.write(`error: ${String(err)}\n`);
      }
      process.exit(1);
    }
  });

  return cmd;
}
